### ISSUE TITLE
Switch to 4 spaces, Take out unnecessary style rules

### ISSUE THREAD

**Issue by joshuagruenstein** [frc5806/Reference#1]
Honestly better than tabs, and the default for most text editors and IDEs.

**Comment by truell20** [comment]
@joshuagruenstein What do you think of downsizing the style guide? Its quite large for its importance. Don't want new members focusing on that a bunch.

**Comment by joshuagruenstein** [comment]
I think we should just move it to a new file, and talk after that.  It's not so long it terms of rules, just comprehensive with explanations.  It'll make more sense scale wise in it's own file.

**Comment by joshuagruenstein** [comment]
On second thought @truell20, we can definitely get rid of #3 and #4.

**Comment by truell20** [comment]
#4?

**Comment by joshuagruenstein** [comment]
I'm referring to 3) Line length and 4) Control structures.

**Comment by truell20** [comment]
Ah the github autolinking made me think that you were talking about issues.

**Comment by truell20** [comment]
Both of those seem unnecessary. I'll take them out.
